#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/a55x

PRODUCT_COPY_FILES += \
    vendor/samsung/a55x/proprietary/recovery/root/vendor/firmware/tsp/gt9895_a55x.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/tsp/gt9895_a55x.bin \
    vendor/samsung/a55x/proprietary/vendor/etc/Khronos/OpenCL/samsung.icd:$(TARGET_COPY_OUT_VENDOR)/etc/Khronos/OpenCL/samsung.icd \
    vendor/samsung/a55x/proprietary/vendor/etc/SoundBoosterParam.txt:$(TARGET_COPY_OUT_VENDOR)/etc/SoundBoosterParam.txt \
    vendor/samsung/a55x/proprietary/vendor/etc/audio_board_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_board_info.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/DQE_coef_data.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/DQE_coef_data.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_atc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_atc.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_atc_ana6710_a55x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_atc_ana6710_a55x.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_bypass.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_bypass.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_colormode0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colormode0.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_colormode0_ana6710_a55x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colormode0_ana6710_a55x.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_colormode0_ana6710_a55x_hdr.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colormode0_ana6710_a55x_hdr.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_colormode0_ana6710_a55x_natural.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colormode0_ana6710_a55x_natural.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_colormode0_ana6710_a55x_vivid0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colormode0_ana6710_a55x_vivid0.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_colormode0_ana6710_a55x_vivid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colormode0_ana6710_a55x_vivid1.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_colormode0_ana6710_a55x_vivid2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colormode0_ana6710_a55x_vivid2.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_colormode0_off.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colormode0_off.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_colormode0_s6e3fc5_a55x.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colormode0_s6e3fc5_a55x.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_colormode0_s6e3fc5_a55x_hdr.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colormode0_s6e3fc5_a55x_hdr.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_colormode0_s6e3fc5_a55x_natural.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colormode0_s6e3fc5_a55x_natural.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_colormode0_s6e3fc5_a55x_vivid0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colormode0_s6e3fc5_a55x_vivid0.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_colormode0_s6e3fc5_a55x_vivid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colormode0_s6e3fc5_a55x_vivid1.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_colormode0_s6e3fc5_a55x_vivid2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colormode0_s6e3fc5_a55x_vivid2.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_colortemp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_colortemp.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_eyetemp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_eyetemp.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_rgbgain.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_rgbgain.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_skincolor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_skincolor.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/dqe/calib_data_whitepoint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dqe/calib_data_whitepoint.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/floating_feature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/floating_feature.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/gnss/ca.pem:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/ca.pem \
    vendor/samsung/a55x/proprietary/vendor/etc/gnss/gps.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.cfg \
    vendor/samsung/a55x/proprietary/vendor/etc/gnss/gps.debug.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.debug.cfg \
    vendor/samsung/a55x/proprietary/vendor/etc/gnss/gps.issuetracker.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.issuetracker.cfg \
    vendor/samsung/a55x/proprietary/vendor/etc/hdr_samsung_mx.key:$(TARGET_COPY_OUT_VENDOR)/etc/hdr_samsung_mx.key \
    vendor/samsung/a55x/proprietary/vendor/etc/init.insmod.vendor_dlkm.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/init.insmod.vendor_dlkm.cfg \
    vendor/samsung/a55x/proprietary/vendor/etc/init/init.baseband.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.baseband.rc \
    vendor/samsung/a55x/proprietary/vendor/etc/init/init.exynos.wifi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.exynos.wifi.rc \
    vendor/samsung/a55x/proprietary/vendor/etc/init/init.fingerprint.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.fingerprint.rc \
    vendor/samsung/a55x/proprietary/vendor/etc/init/init.gps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps.rc \
    vendor/samsung/a55x/proprietary/vendor/etc/init/init.gps.rose.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps.rose.rc \
    vendor/samsung/a55x/proprietary/vendor/etc/init/init.nfc.samsung.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.nfc.samsung.rc \
    vendor/samsung/a55x/proprietary/vendor/etc/init/init.sensorhub.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.sensorhub.rc \
    vendor/samsung/a55x/proprietary/vendor/etc/init/init.vendor.onebinary.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.onebinary.rc \
    vendor/samsung/a55x/proprietary/vendor/etc/init/init.vendor.rilcommon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.rilcommon.rc \
    vendor/samsung/a55x/proprietary/vendor/etc/init/teegris.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/teegris.rc \
    vendor/samsung/a55x/proprietary/vendor/etc/init/vendor.samsung.hardware.gnss-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.gnss-service.rc \
    vendor/samsung/a55x/proprietary/vendor/etc/init/vendor.samsung.rilchip.slsi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rilchip.slsi.rc \
    vendor/samsung/a55x/proprietary/vendor/etc/init/vendor.samsung.rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rild.rc \
    vendor/samsung/a55x/proprietary/vendor/etc/init/wifi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi.rc \
    vendor/samsung/a55x/proprietary/vendor/etc/init/wifi_slsi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi_slsi.rc \
    vendor/samsung/a55x/proprietary/vendor/etc/libnfc-sec-vendor.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-sec-vendor.conf \
    vendor/samsung/a55x/proprietary/vendor/etc/libse-gto-hal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libse-gto-hal.conf \
    vendor/samsung/a55x/proprietary/vendor/etc/locale/plmn_delta_eng.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_eng.bin \
    vendor/samsung/a55x/proprietary/vendor/etc/locale/plmn_delta_zh-rCN.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rCN.bin \
    vendor/samsung/a55x/proprietary/vendor/etc/locale/plmn_delta_zh-rHK.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rHK.bin \
    vendor/samsung/a55x/proprietary/vendor/etc/locale/plmn_delta_zh-rTW.bin:$(TARGET_COPY_OUT_VENDOR)/etc/locale/plmn_delta_zh-rTW.bin \
    vendor/samsung/a55x/proprietary/vendor/etc/media_codecs_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_c2.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/media_codecs_performance_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_c2.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/mixer_usb_default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_usb_default.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/mixer_usb_gray.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_usb_gray.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/mixer_usb_white.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_usb_white.xml \
    vendor/samsung/a55x/proprietary/vendor/etc/nfc/sec_s3nsen6_hwreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/sec_s3nsen6_hwreg.bin \
    vendor/samsung/a55x/proprietary/vendor/etc/nfc/sec_s3nsen6_swreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/sec_s3nsen6_swreg.bin \
    vendor/samsung/a55x/proprietary/vendor/etc/plmn_delta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta.bin \
    vendor/samsung/a55x/proprietary/vendor/etc/plmn_delta_attaio.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_attaio.bin \
    vendor/samsung/a55x/proprietary/vendor/etc/plmn_delta_hktw.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_hktw.bin \
    vendor/samsung/a55x/proprietary/vendor/etc/plmn_delta_ltn.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_ltn.bin \
    vendor/samsung/a55x/proprietary/vendor/etc/plmn_delta_usagsm.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_usagsm.bin \
    vendor/samsung/a55x/proprietary/vendor/etc/plmn_se13_prebuilt.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_se13_prebuilt.bin \
    vendor/samsung/a55x/proprietary/vendor/etc/wifi/init.insmod.wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/init.insmod.wifi.cfg \
    vendor/samsung/a55x/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/samsung/a55x/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/samsung/a55x/proprietary/vendor/firmware/APBargeIn_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APBargeIn_AUDIO_SLSI.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/APDVRX_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APDVRX_AUDIO_SLSI.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/APDVTX_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APDVTX_AUDIO_SLSI.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/AP_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/AP_AUDIO_SLSI.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/OD_V3.4.10_11_17_QVGA_ROSE_ENN_BGRA.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V3.4.10_11_17_QVGA_ROSE_ENN_BGRA.nnc \
    vendor/samsung/a55x/proprietary/vendor/firmware/OD_V3.5.3_06_12_VGA_ROSE_ENN_BGRA.nnc:$(TARGET_COPY_OUT_VENDOR)/firmware/OD_V3.5.3_06_12_VGA_ROSE_ENN_BGRA.nnc \
    vendor/samsung/a55x/proprietary/vendor/firmware/RTP_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_1.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/RTP_119.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_119.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/RTP_124.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_124.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/RTP_2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_2.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/RTP_41.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_41.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/RTP_5.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/RTP_5.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SM-A556B/AIE.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SM-A556B/AIE.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SM-A556B/calliope_sram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SM-A556B/calliope_sram.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SM-A556B/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SM-A556B/mfc_fw.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SM-A556B/os.checked.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SM-A556B/os.checked.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SM-A556B/pablo_icpufw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SM-A556B/pablo_icpufw.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SM-A556B/vts.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SM-A556B/vts.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SM-A556B/wifi/mx140.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SM-A556B/wifi/mx140.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SM-A556B/wifi/slsi_reg_database.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SM-A556B/wifi/slsi_reg_database.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SM-A556E/AIE.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SM-A556E/AIE.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SM-A556E/calliope_sram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SM-A556E/calliope_sram.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SM-A556E/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SM-A556E/mfc_fw.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SM-A556E/os.checked.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SM-A556E/os.checked.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SM-A556E/pablo_icpufw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SM-A556E/pablo_icpufw.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SM-A556E/vts.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SM-A556E/vts.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SM-A556E/wifi/mx140.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SM-A556E/wifi/mx140.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SM-A556E/wifi/slsi_reg_database.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SM-A556E/wifi/slsi_reg_database.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SoundAlive.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SoundAlive.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/SoundBoosterParam.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SoundBoosterParam.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/a2dpcom.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a2dpcom.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/abox_solution.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_solution.conf \
    vendor/samsung/a55x/proprietary/vendor/firmware/abox_solution_rev00.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_solution_rev00.conf \
    vendor/samsung/a55x/proprietary/vendor/firmware/abox_solution_ti.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_solution_ti.conf \
    vendor/samsung/a55x/proprietary/vendor/firmware/abox_system.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_system.conf \
    vendor/samsung/a55x/proprietary/vendor/firmware/abox_tplg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/abox_tplg.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.conf \
    vendor/samsung/a55x/proprietary/vendor/firmware/avsyncmix.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/avsyncmix.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/calliope_dram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_dram.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/camera_tilt_calibration_info_1_2:$(TARGET_COPY_OUT_VENDOR)/firmware/camera_tilt_calibration_info_1_2 \
    vendor/samsung/a55x/proprietary/vendor/firmware/compress_capture.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/compress_capture.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/cs40l26.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26.wmfw \
    vendor/samsung/a55x/proprietary/vendor/firmware/dax_param.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dax_param.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/default_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/default_configuration.flm.cfg.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/dolby.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dolby.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/gnss/firmware_signed_a55xnaxx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_a55xnaxx.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/gnss/firmware_signed_a55xnsxx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gnss/firmware_signed_a55xnsxx.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/icc_profile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/icc_profile.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/lc3dec.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lc3dec.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/lc3enc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/lc3enc.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/listenbackeffect.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/listenbackeffect.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/param_ti.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/param_ti.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/rear3_dualcal_param.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/rear3_dualcal_param.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/rxse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/rxse.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/sb_ll.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_ll.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/sb_music.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_music.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/sb_others.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_others.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/sectiongraph_tplg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sectiongraph_tplg.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/sectiongraph_tplg.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/sectiongraph_tplg.conf \
    vendor/samsung/a55x/proprietary/vendor/firmware/secure_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/secure_configuration.flm.cfg.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/setfile_gc05a3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_gc05a3.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/setfile_gn5.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_gn5.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/setfile_imx258.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_imx258.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/setfile_imx616.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_imx616.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/setfile_imx906.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_imx906.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/spkamp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/spkamp.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/tee/A556EXXSABYI4/00000000-0000-0000-0000-0053545354ab:$(TARGET_COPY_OUT_VENDOR)/firmware/tee/A556EXXSABYI4/00000000-0000-0000-0000-0053545354ab \
    vendor/samsung/a55x/proprietary/vendor/firmware/tee/A556EXXSABYI4/00000000-0000-0000-0000-46494e474552:$(TARGET_COPY_OUT_VENDOR)/firmware/tee/A556EXXSABYI4/00000000-0000-0000-0000-46494e474552 \
    vendor/samsung/a55x/proprietary/vendor/firmware/tee/A556EXXSABYI4/00000000-0000-0000-0000-474154454b45:$(TARGET_COPY_OUT_VENDOR)/firmware/tee/A556EXXSABYI4/00000000-0000-0000-0000-474154454b45 \
    vendor/samsung/a55x/proprietary/vendor/firmware/tee/A556EXXSABYI4/00000000-0000-0000-0000-4b45594d5354:$(TARGET_COPY_OUT_VENDOR)/firmware/tee/A556EXXSABYI4/00000000-0000-0000-0000-4b45594d5354 \
    vendor/samsung/a55x/proprietary/vendor/firmware/tee/A556EXXSABYI4/driver/00000000-0000-0000-0000-494363447256:$(TARGET_COPY_OUT_VENDOR)/firmware/tee/A556EXXSABYI4/driver/00000000-0000-0000-0000-494363447256 \
    vendor/samsung/a55x/proprietary/vendor/firmware/tee/A556EXXSABYI4/driver/00000000-0000-0000-0000-53626f786476:$(TARGET_COPY_OUT_VENDOR)/firmware/tee/A556EXXSABYI4/driver/00000000-0000-0000-0000-53626f786476 \
    vendor/samsung/a55x/proprietary/vendor/firmware/tfa9878.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa9878.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/samsung/a55x/proprietary/vendor/firmware/tismartpa_driver_tuning.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tismartpa_driver_tuning.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/tsp/gt9895_a55x.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tsp/gt9895_a55x.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/txse1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/txse1.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/txse2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/txse2.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/volctrl.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/volctrl.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/volumemonitor.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/volumemonitor.bin \
    vendor/samsung/a55x/proprietary/vendor/firmware/wifi/hydra_config.sdb:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/hydra_config.sdb \
    vendor/samsung/a55x/proprietary/vendor/firmware/wifi/mx140/wpal:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140/wpal \
    vendor/samsung/a55x/proprietary/vendor/firmware/wifi/mx140_bt.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_bt.hcf \
    vendor/samsung/a55x/proprietary/vendor/firmware/wifi/mx140_common.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_common.hcf \
    vendor/samsung/a55x/proprietary/vendor/firmware/wifi/mx140_wlan.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_wlan.hcf \
    vendor/samsung/a55x/proprietary/vendor/firmware/wifi/mx140_wlan_sw.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_wlan_sw.hcf \
    vendor/samsung/a55x/proprietary/vendor/firmware/wifi/mx140_wlan_t.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_wlan_t.hcf \
    vendor/samsung/a55x/proprietary/vendor/firmware/wifi/mx140_wlan_t_sw.hcf:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi/mx140_wlan_t_sw.hcf \
    vendor/samsung/a55x/proprietary/vendor/tee/00000000-0000-0000-0000-0053545354ab:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-0053545354ab \
    vendor/samsung/a55x/proprietary/vendor/tee/00000000-0000-0000-0000-46494e474552:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-46494e474552 \
    vendor/samsung/a55x/proprietary/vendor/tee/00000000-0000-0000-0000-474154454b45:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-474154454b45 \
    vendor/samsung/a55x/proprietary/vendor/tee/00000000-0000-0000-0000-4b45594d5354:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-4b45594d5354 \
    vendor/samsung/a55x/proprietary/vendor/tee/driver/00000000-0000-0000-0000-4d53546d7374:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-0000-0000-0000-4d53546d7374 \
    vendor/samsung/a55x/proprietary/vendor/tee/driver/00000000-0000-0000-0000-53626f786476:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-0000-0000-0000-53626f786476 \
    vendor/samsung/a55x/proprietary/vendor_ramdisk/lib/firmware/sgpu/vangogh_lite_unified_evt0_b.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/lib/firmware/sgpu/vangogh_lite_unified_evt0_b.bin \
    vendor/samsung/a55x/proprietary/vendor_ramdisk/lib/firmware/sgpu/vangogh_lite_unified_evt0_e.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/lib/firmware/sgpu/vangogh_lite_unified_evt0_e.bin \
    vendor/samsung/a55x/proprietary/vendor_ramdisk/vendor/firmware/tsp/gt9895_a55x.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/vendor/firmware/tsp/gt9895_a55x.bin

PRODUCT_PACKAGES += \
    libEGL_samsung \
    libGLESv1_CM_samsung \
    libGLESv2_samsung \
    gnss_aidl_lib \
    camera.s5e8845 \
    vulkan.samsung \
    libIRTA \
    libOpenCL \
    libSGPUOpenCL \
    libSamsungPostProcessConvertor \
    libVendorSemDataProps \
    libVendorSemTelephonyProps \
    lib_SoundAlive_3DPosition_ver202 \
    lib_SoundAlive_AlbumArt_ver105 \
    lib_SoundAlive_SRC384_ver330 \
    lib_SoundAlive_play_plus_ver600 \
    lib_SoundBooster_ver2000 \
    lib_soundaliveresampler \
    libcrypto-v34 \
    libegis_fp_normal_sensor_test \
    libeis_core \
    libeis_interface \
    libenn_common_utils \
    libenn_cpu_operators \
    libenn_engine_lib \
    libenn_model \
    libenn_public_api_cpp_lib \
    libenn_user_driver_cpu \
    libenn_user_driver_gpu_lib \
    libenn_user_driver_unified \
    libenn_user_lib \
    libexynos_sensor_interface \
    libfloatingfeature \
    libhwjsqz \
    libmpbase \
    libprofileparamstorage \
    libril_sem \
    libsec-ril-impl \
    libsec2lsi_conversion \
    libsecaudiocoreutils \
    libsecaudioinfo \
    libsecnativefeature \
    libsecril-client \
    libsemnativecarrierfeature \
    libsemseg \
    libsensorlistener \
    libsfp_sensor \
    libsfp_teegw \
    libskeymint10device \
    libskeymint_cli \
    libspatializerparamstorage \
    libteecl \
    libuniapi \
    libuniplugin \
    libuuid_vendor \
    libvpl \
    libwrappergps \
    sensors.inputvirtual \
    sensors.sensorhub \
    libaudioeffectoffload \
    libaudiosaplus_sec \
    libmyspace \
    libswdap \
    libswspatializer \
    vendor.samsung.hardware.biometrics.fingerprint-V1-ndk \
    vendor.samsung.hardware.gnss-V3-ndk \
    vendor.samsung.hardware.radio-V1-ndk \
    vendor.samsung.hardware.radio.bridge-V1-ndk \
    vendor.samsung.hardware.radio.channel-V1-ndk \
    vendor.samsung.hardware.radio.data-V1-ndk \
    vendor.samsung.hardware.radio.messaging-V1-ndk \
    vendor.samsung.hardware.radio.sim-V1-ndk \
    vendor.samsung.hardware.thermal-V1-ndk \
    vendor.samsung.hardware.thermal@1.0 \
    vendor.samsung_slsi.hardware.enn_aidl-V1-ndk \
    com.google.android.widevine.nonupdatable \
    vendor.samsung.hardware.radio.exclude.slsi.xml \
    vendor.samsung.hardware.radio_manifest_2_34.xml \
    vendor.samsung.hardware.sehradio_manifest_2_34.xml \
    gps \
    gpsd_K44 \
    rild \
    vendor.samsung.hardware.gnss-service \
    init.insmod \
    tzdaemon \
    tzts_daemon

PRODUCT_PACKAGES += \
    vendor_Khronos_OpenCL_vendors_samsung_icd
